TODO_plugin_name:
  app_auth_host:
    default: ""
    client: false
  amqp_connect_string:
    default: ""
    client: false
  plugin_discourse_api_secret:
    default: ""
    client: false
  max_upload_videos_user_per_day:
    default: 5
    client: false
    max: 5
  max_upload_video_size:
    default: 50
    client: false
    max: 50
